### PR TITLE
feat: moved piano footstool closer to piano to prevent camera issues

### LINKED ISSUE #230: Piano footstool prevents 47 getting past Kronstadt chair
The piano living room cosmetic contains a footstool which, if selected with the kronstadt chair close by, causes a problem where 47 cannot pass it. This also causes a camera freakout if 47 gets up from sitting down on said chair.

BEFORE:
screenshot_8115

AFTER:
image

### PR DESCRIPTION
**Pull request by dribbleondo**
fixes #230

### CODE REVIEW

**Comment by Ocean-Minnow** [comment]
This is tested and functional, but for some reason something about moving a prop bothers something in my mind. I can't place why at all so I'll give it a bit for anyone else to give potential feedback then merge if I still can't figure out what's nibbling at me.

**Comment by Ocean-Minnow** [comment]
> You were fine with moving the Paris cake for a potential piece of intel though. 😝

No I wasn't! I suggested like 30 other solutions and I have no idea why that bothered me either! 😄

**Comment by VoodooHillbilly** [comment]
Ah ok. I completely forgot about that. That one bugged me too.

To me, it seems fine to move this footstool (hassock?) enough that it doesn't conflict with the chair animations & camera. Currently the fix moves it too close to the piano.

**Comment by dribbleondo** [comment]
> To me, it seems fine to move this footstool (hassock?) enough that it doesn't conflict with the chair animations & camera. Currently the fix moves it too close to the piano.

If I put it closer to the chair, then there's a squeeze with a gap between the piano and the footstool that looks possible to pass, when it isn't. Putting it closer to the Piano avoids that.

While I agree, short of moving the piano and the chair behind the Piano also, I can't really do much about it.

**Comment by dribbleondo** [comment]
> This is tested and functional, but for some reason something about moving a prop bothers something in my mind. I can't place why at all so I'll give it a bit for anyone else to give potential feedback then merge if I still can't figure out what's nibbling at me.

This isn't any different to what IO did to a part of Colorado when they moved a few props around to clear up some traversal back in 2023.

**Comment by VoodooHillbilly** [comment]
> If I put it closer to the chair, then there's a squeeze with a gap between the piano and the footstool that looks possible to pass, when it isn't. Putting it closer to the Piano avoids that.

Yeah that makes sense. The collision boxes can be really bad.

> This isn't any different to what IO did to a part of Colorado when they moved a few props around to clear up some traversal back in 2023.

The difference there is IOI officially chose to move them for a fix vs us unofficially moving desserts and furniture to avoid bugs they haven't addressed. Not a huge difference for some people, but it leads to subjective opinions about where things "should" go.

**Comment by dribbleondo** [comment]
> The difference there is IOI officially chose to move them for a fix vs us unofficially moving desserts and furniture to avoid bugs they haven't addressed. Not a huge difference for some people, but it leads to subjective opinions about where things "should" go.

Let's rundown what this patch does:

This is moving a footstool in the safehouse to fix a squeeze issue. A place that is neither in combat, nor able to have guns be used inside the cripple box which affects 96% of the safehouse. If this change was made in Colorado, or really anywhere else in the main game, sure, I could at least understand the argument presented here. We shouldn't be making balance decisions, even if it's moving a table slightly; leave that to IO. The safehouse a pacified zone where only a very small mount of actions are allowed, and only in specific places.

This patch specifically should not be a controversial change.

**Comment by VoodooHillbilly** [comment]
A "few" dozen cm would be more accurate. The new position so close to the piano looks bad. Have you tried rotating the chair slightly?

**Comment by Ocean-Minnow** [comment]
I will also add that I was completely able to walk between the piano and the footstool without this patch, and the chair was accessible and usable from both sides, so I only view this as an issue with the camera.

> [...] the safehouse is a pacified, neutral zone where only a very small amount of actions are allowed, and only in specific places. Moving a footstool is not gonna change the gameplay balance of anything related to the safehouse. This is to clear up a squeeze, it's not providing extra cover in a gun battle or making it easier to get to your target.

This is kind of a moot point - since the safehouse is only about aesthetics and visuals, only the aesthetics and visuals matter, and so we should be paying attention to how the aesthetics and visuals are affected by any changes.

**Comment by dribbleondo** [comment]
> I only view this as an issue with the camera. For that reason, I think that moving it as little as is needed to not make the camera bug would be the best course of action.

Fine, I'll readjust the collision box and the footstall to adhere to that.

> only the aesthetics and visuals matter, and so we should be paying attention to how the aesthetics and visuals are affected by any changes.

Yes, **that is rather my point.**

**Comment by dribbleondo** [comment]
image

Is this satisfactory? I also rotated the collision box for the kronstadt chair as that was also causing issues. Both sides are now accessible by walking.

**Comment by dribbleondo** [comment]
Updated the file with the new entity changes and values.

**Comment by Ocean-Minnow** [comment]
I'll wait for @VoodooHillbilly 's opinion before I make any calls myself.

**Comment by VoodooHillbilly** [comment]
LGTM now.

**Comment by Ocean-Minnow** [comment]
Well in that case, *I* have a problem with it...

Nah, I'm just kidding :p

**Pull request merged**
