### PR TITLE
feat: change sitting animation on 47's bedroom balcony sunbed to match the sunbed outside

### LINKED ISSUE #226: Sunbed on 47's bedroom balcony has the wrong sitting animation
He should be laying down on it, like he does in Bangkok or in the sunbed on the bottom floor.

Changed the entity to remove the original sunbed and replaced it with the entity instead:
screenshot_8110

(also to anyone wondering, 47 really _does_ sit that far to the right on the sunbed, that's not a bug specific to this mod).

### PR DESCRIPTION
**Pull request by dribbleondo**
fixes #226

### CODE REVIEW

**Comment by VoodooHillbilly** [comment]
Did you intend to move these, or did Glacier Kit add more unrelated `m_mTransform` changes?
- 5e5f0e35f3b8f107 Vase_Italy_E_Small_01
- 7d8c712ada43d797 chair_relaxing_hokaido_b_01

**Comment by dribbleondo** [comment]
> Did you intend to move these, or did Glacier Kit add more unrelated `m_mTransform` changes?
> 
> * 5e5f0e35f3b8f107 Vase_Italy_E_Small_01
> * 7d8c712ada43d797 chair_relaxing_hokaido_b_01

Checking this now; I recall the latter is deliberate, but the former definitely isn't.

**Comment by dribbleondo** [comment]
Done.

**Comment by VoodooHillbilly** [comment]
LGTM now.

**Comment by Ocean-Minnow** [comment]
I'm holding off on merging this until I can clear up the confusion on the issue page. 47 is already laying down in that image, so what does this patch change exactly?

**Comment by dribbleondo** [comment]
> I'm holding off on merging this until I can clear up the confusion on the issue page. 47 is already laying down in that image, so what does this patch change exactly?

He's sitting normally. This patches change it to laying down.

**Comment by Ocean-Minnow** [comment]
Ah, I see. Are you sure this is a bug and not an intentional design choice?

**Comment by dribbleondo** [comment]
Considering all the other sunbeds in WOA are either ones you lay down on or cannot access, I'd say this is a _bizaare_ choice if it's intentional. This keeps it consistent with other sunbeds. Not necessarily a bug, but certainly a weird inconsistency.

I'd even go so far as to say that this was probably a placeholder until they linked up the right entity (which they did do on the sunbed downstairs).

**Comment by VoodooHillbilly** [comment]
Is this animation applying to all the furniture for you too?
chair1
chair2

**Comment by Ocean-Minnow** [comment]
> I'd even go so far as to say that this was probably a placeholder until they linked up the right entity

This doesn't make sense to me. You're saying they only placed down half a deck chair (despite their editor bundling such things together), but did bother to put in a different interaction animation (which I really doubt requires less effort), and then just left it for long enough that they managed to forget to replace it? How would that happen?

Why put in a placeholder animation at all? Why not simply leave the object non-interactable until it's got the right animation? It just doesn't add up :/

**Comment by dribbleondo** [comment]
> Is this animation applying to all the furniture for you too? chair1 chair2

Oh god, that's not something I noticed. How is that happening?!

I'm gonna close this issue, mostly because there isn't much of a consensus, and I'm starting to think this might be out of scope for the mod.

**Pull request closed without merging**
